### PR TITLE
Changing dealer behaviour (draw till 17)

### PR DESCRIPTION
**Pull request by XargsUK**
Change the dealer behaviour to draw cards if count is below 17. Previously was 16, though this is not typical in blackjack and gives the dealer an even greater edge.

### CODE REVIEW

**Comment by aikaterna** [comment]
I spoke with Redjumpman and he approves this change, but could I get you to also increment the version in casino.py? 2.4.9 would be fine.

**Comment by XargsUK** [comment]
@aikaterna will do this now

**Comment by XargsUK** [comment]
Incremented the version number in casino.py @aikaterna

**Comment by aikaterna** [comment]
Thanks man.

**Pull request merged**
