### PR TITLE
Cookie patch

### PR DESCRIPTION
**Pull request by Mamalus**
Fixed when users are still able to get negative cookies when being stolen.

### CODE REVIEW

**Comment by Redjumpman** [comment]
I am having trouble understanding what you are saying. Also adding a return msg in that if statement has no affect.

**Comment by skeith** [comment]
I am also lost here

**Comment by Mamalus** [comment]
Cause someone was able to steal someone that has 0 and it went through causing them to have -negative amount. I thought that would be a fix though.

**Comment by Mamalus** [comment]
NVM sorry RJM it was my fault

**Pull request closed without merging**
